### ISSUE TITLE
Thank you and can I buy you a coffee?

### ISSUE THREAD

**Issue by SimonMerrett** [MitjaNemec/ReplicateLayout#1]
Just wanted to say thanks for all the work you do on these plugins and ask if there's any way I can encourage you or support a little. Your plugin has saved me a lot of time and I'm really looking forward to doing the same in KiCad 6. I bet you have saved people so much time at the expense of your own, so it would be nice to have a way to say thank you.

**Comment by MitjaNemec** [comment]
Hi, saying thanks is enough, as I don't have nor do I intend to set up any donation options. (librepay, buymeacoffe, patreon or anything else). As for the support, if somebody would volunteer to write proper documentation for the plugins that would be great. But if you'd really like to contribute financially, donate to KiCad. Maybe we'll get proper python API sooner.

Anyhow, thanks for the feedback. It is always nice to hear that my work is appreciated.

**Comment by SimonMerrett** [comment]
I just donated to KiCad this month, to take advantage of the KiPro Services funding match. I will have a go at updating docs for the 6.0 releases if you like?

**Comment by MitjaNemec** [comment]
Yeah, that would be really great. You can start with [Archive 3D Models](https://github.com/MitjaNemec/Archive3DModels) and [Place Footprints]( https://github.com/MitjaNemec/PlaceFootprints), which are already available through V6 PCM. Place Footprints plugin is more or less the same, while Archive 3D Models plugin is basically a stripped down version of V5 ArchiveProject plugin.

So for start you can start by cloning plugin's repo, and adding a README.md, with basic info. Basic markdown syntax is easy to look-up if you are not familiar with

**Comment by MitjaNemec** [comment]
Once you're done, you can open a pull request and we'll marge your work here

**Comment by MitjaNemec** [comment]
If you'll publish the documentation elsewhere we can add the link to it within the PCM
