### ISSUE TITLE
Option to ignore locked zones/graphics

### ISSUE THREAD

**Issue by liborw** [MitjaNemec/ReplicateLayout#17]
Hi, great plugin, I'm using it all the time, what I'm missing is option to ignore locked graphics and zones. I usually has cad drawing for reference which is locked and most of the time hidden, but when I make it visible I usually find a big mess of lines.

**Comment by MitjaNemec** [comment]
Thanks for the idea. Feature is implemented in 1.2.0. It might take a while before it becomes available in PCM
