### ISSUE TITLE
I press ok and replication does not occur, nothing happens at all. The window does not close.

### ISSUE THREAD

**Issue by lincvv** [MitjaNemec/ReplicateLayout#19]
![Screenshot_2](https://user-images.githubusercontent.com/13439389/184154343-357490dc-0051-40c5-84dd-dc724ecbbc4e.png)

**Comment by MitjaNemec** [comment]
This is due to #18. Fix has been commited, but it has not been yet published within PCM.

In the mean time you can install any older version available from releases page

**Comment by MitjaNemec** [comment]
Or even better you can install the newest one

**Comment by MitjaNemec** [comment]
1.2.1

**Comment by MitjaNemec** [comment]
The fix should be available in PCM now
