### ISSUE TITLE
Selecting Remove existing tracks/zones/drawings deletes items from source layout

### ISSUE THREAD

**Issue by sslupsky** [MitjaNemec/ReplicateLayout#2]
Noticed an issue today where if the "Remove existing tracks/zones/drawings" is checked, some items in the source layout are removed.  The destination layout includes the missing items.

Here are a couple screenshots that illustrate the issue.  Note in the second illustration, the GND tracks and via's are missing as well as the AUXOUT stub.

Source layout before replications:
![Screen Shot 2022-02-01 at 11 40 49 AM](https://user-images.githubusercontent.com/16888734/152030913-937ed0c0-d517-486a-adbd-5d0e999056bb.png)

Source layout after replication:
![Screen Shot 2022-02-01 at 11 41 30 AM](https://user-images.githubusercontent.com/16888734/152030940-593112c7-89a2-4da2-8e46-214b9cfde1ca.png)

Destination layout after replication:
![Screen Shot 2022-02-01 at 11 59 48 AM](https://user-images.githubusercontent.com/16888734/152033324-a2a4e058-af23-4cf7-8a56-3e41182b61ef.png)

**Comment by MitjaNemec** [comment]
Hi, thanks for reporting. Can you share this project? Or can you at least supply similar project, where you can recreate this issue?

**Comment by sslupsky** [comment]
Here you go.
[replicate_issue_2.zip](https://github.com/MitjaNemec/ReplicateLayout/files/7982036/replicate_issue_2.zip)

**Comment by MitjaNemec** [comment]
OK, I can replicate the issue. But it will take some time until I find the bug

**Comment by MitjaNemec** [comment]
Found the source of the bug, and fixed it. The bug was present also in 5.1.x release and it was present for quite a while. Again thanks for spotting it and reporting it.

But the fix will take a while to be published in PCM. You can download the latest release from Github and install it from file

**Comment by sslupsky** [comment]
That is great.  Thank you.

**Comment by sslupsky** [comment]
I downloaded the update.  It's actually worse now ... all the nets disappear and the zones as well in the source layout.  I'll update my layout and upload again so you can reproduce.

**Comment by sslupsky** [comment]
I reverted to 1.0.1 and the problem seems the same.  Perhaps my update did not work correctly.  I'll let you know if I figure this out.
