### ISSUE TITLE
Exception Error "AttributeError: module 'pcbnew' has no attribute 'EDA_RECT' 

### ISSUE THREAD

**Issue by TheHexaCube** [MitjaNemec/ReplicateLayout#26]
Hey, 

using the latest nightly i am encountering the following error message when trying to run the plugin: 

![ENQZHcZ](https://user-images.githubusercontent.com/4275772/202572402-04211612-db56-4160-84c7-6bd53b540600.png)

Version Info: 

![image_2022-11-17_232804766](https://user-images.githubusercontent.com/4275772/202573534-4b2fa2ec-9b4e-4995-93b1-13991e7726ee.png)

**Comment by MitjaNemec** [comment]
Yeah, I am currently not supporting the 6.99. There is a PR #13 which should fix this, so you might try this.

As I still haven't figured out how to have two releases of the plugin available (one for 6.0.x and the other for 6.99) you are on your own.

**Comment by MitjaNemec** [comment]
There are now there are two versions of plugin available. Version 1.x.y is compatible with KiCad 6.0.x and version 2.x.y is compatible with KiCad 6.99+.
