### ISSUE TITLE
Selected anchor footprint is on the schematic sheet which does not have multiple instances.

### ISSUE THREAD

**Issue by JarrettR** [MitjaNemec/ReplicateLayout#32]
I've created a new project, with a hierarchical sheet, and a few components, and then copied that sheet.

![image](https://user-images.githubusercontent.com/6027644/208792265-2a444cf7-513f-4ae2-8f89-b8068d100d42.png)

![image](https://user-images.githubusercontent.com/6027644/208792287-525813c7-99e2-4bee-9f99-9badd76203b8.png)

![image](https://user-images.githubusercontent.com/6027644/208792401-d85381c4-b079-4183-b564-48c88b3df65c.png)

Here's the generated log:

```
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 326:Plugin executed on: 'linux'
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 327:Plugin executed with python version: '3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]'
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 328:KiCad build version: 6.0.10-86aedd382b~118~ubuntu22.04.1
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 329:Plugin version: 1.2.6
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 330:Frame repr: <wx._core.Frame object at 0x7f5d8b1e6050>
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 354:Preparing replicator with R1 as a reference
12-20 16:31:55 com_github_MitjaNemec_ReplicateLayout.replicate_layout 110:getting a list of all footprints on board
```

I went back and checked version 1.2.4 and it seemed to work.

**Comment by MitjaNemec** [comment]
Thanks for reporting. As you've noted, this bug was introduced in the latest version. I am aware of it but I'll fix it toggother with #31 and #30. I just have to find the time to test the solution on Linux and Windows.
