### ISSUE TITLE
Replicated Text Position Error

### ISSUE THREAD

**Issue by myamigo** [MitjaNemec/ReplicateLayout#35]
The project in [Replicate_Text_Error.zip](https://github.com/MitjaNemec/ReplicateLayout/files/10375897/Replicate_Text_Error.zip) exposes this issue.

The project consists of 3 copies of a sheet containing 1 connector. The PCB places the seed component (J1) at (100,100) with the drill origin at (150,100).

J2 and J3 are first positioned relative to J1 and then rotated ±120° around the drill origin so we have this as a starting point...
![image](https://user-images.githubusercontent.com/17319745/211382210-4cf54c78-1b04-4237-b06a-9697d63ea2bb.png)

Next run the replicator using J1 as the seed with all defaults selected...
![image](https://user-images.githubusercontent.com/17319745/211382561-922e1b7e-7092-4905-8bad-751f72ee7899.png)

... and when finished you will notice that the text for J2 & J3 are repositioned slightly and that the ref text actually overlaps the pads. This triggered an unexpected DRC error, which revealed the problem.

![image](https://user-images.githubusercontent.com/17319745/211382712-0c32bc0e-456e-4fb7-a37c-2d59b2fbcf35.png)

![image](https://user-images.githubusercontent.com/17319745/211383139-f2beb61d-30bf-44c0-8209-7c456b3f3b7b.png)
![image](https://user-images.githubusercontent.com/17319745/211383168-9107752d-99a2-4bdd-8279-056e296d232b.png)
![image](https://user-images.githubusercontent.com/17319745/211383208-a37bfe20-ba7e-4d55-8c43-5059500857cc.png)

**Comment by MitjaNemec** [comment]
Whoa, it seems I have a numerical resolution problem somewhere. Thanks for being meticulous enough to spot this and especially for following through and reporting it. I really appreciate it.

**Comment by myamigo** [comment]
Glad to help! I also discovered that the "Keep upright" property for text in footprints now shows that relative to the side of the display rather than the bottom. I reported this in https://gitlab.com/kicad/code/kicad/-/issues/13460

I am hoping this gets resolved by the KiCad team. If that is valid maybe you could add a comment to raise the flag higher?

**Comment by MitjaNemec** [comment]
Well thanks again for spotting this and reporting with a clear test case. It stayed hidden for a really long time.

Anyhow the release is available for manual (from file) installation at https://github.com/MitjaNemec/ReplicateLayout/releases/tag/1.2.11

It will take a while before it is available via PCM as I'd like to cherry pick this also in V7 compatible version, but I am having some issues.

**Comment by myamigo** [comment]
Tested 1.2.11 on my design and it's good. Thank you for handling this one.
