### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by MarkusSBS** [MitjaNemec/ReplicateLayout#44]
Hello 
I have the problem that i get the error  list index out of range 

![image](https://user-images.githubusercontent.com/120729391/226971904-3a6a4e24-9a36-4015-af6f-63bf3342ae61.png)

the project has 40 pages and i want to replicate a circuit 14 times

[replicate_layout.log](https://github.com/MitjaNemec/ReplicateLayout/files/11042367/replicate_layout.log)

**Comment by MitjaNemec** [comment]
Thanks for reporting this. As I can see you are running plugin version 1.2.5. You should update to the latest version (1.3.3) as I think this bug has been fixed.

**Comment by MitjaNemec** [comment]
Please report back in any case (success or failure)
