### ISSUE TITLE
Failure on start V7/2.0.12

### ISSUE THREAD

**Issue by myamigo** [MitjaNemec/ReplicateLayout#55]
I'm starting to look closer at V7 to see how it handles my V6 design. I opened and saved it in V7 so the design files are up to date.

When I run the replicator I get the following...
![image](https://github.com/MitjaNemec/ReplicateLayout/assets/17319745/323ac09c-dd52-48da-8b91-f0367400ae43)

**replicate_layout_error.log** contains only:

> SyntaxError('invalid syntax', ('C:\\Users\\me\\OneDrive\\Documents\\KiCad\\7.0\\3rdparty\\plugins\\com_github_MitjaNemec_ReplicateLayout\\replicate_layout.py', 1069, 43, '                new_text = text.Duplicate(.Cast()\n'))

What do you suggest?

**Comment by myamigo** [comment]
Looks like line 1069 should be 

`
new_text = text.Duplicate(text.Cast())
`

currently it is...

`
new_text = text.Duplicate(.Cast()
`

**Comment by MitjaNemec** [comment]
Yeah I was working to fast yesterday and I got a syntax error in.

The line should be
```
new_text = text.Duplicate().Cast()
```
The fix is in [2.0.13](https://github.com/MitjaNemec/ReplicateLayout/releases/tag/2.0.13)

**Comment by myamigo** [comment]
I just realized I didn't quite have it right. Thanks for the fix.

Got by that and ran into the exotic connectivity popup again. Same issue with the net-tie stubbed nets :-(
