### ISSUE TITLE
Replicate Layout Doesn't work

### ISSUE THREAD

**Issue by pifor71** [MitjaNemec/ReplicateLayout#62]
Hi,
I'm using Kicad 5.1.12 on OS X 11.7
When I try to launch the plugin, an error message appear.
I attach you the Log file.

Thanks for help!

SyntaxError('invalid syntax', ('/Users/monmacbook/Library/Preferences/kicad/scripting/plugins/ReplicateLayout-7/action_replicate_layout.py', 262, 91, '                    report_string = report_string + f"Footprint {item[0]}, pad {item[1]}\\n"\n'))

**Comment by MitjaNemec** [comment]
The replicate layout plugin available from this repository support onlc KiCad V6 (plugin version 1.3.5) and KiCad V7 (plugin version 2.1.3)

There is a replicate layout plugin version which supports KiCad 5.1.x but you can find it in https://github.com/MitjaNemec/Kicad_action_plugins.
