### ISSUE TITLE
Fatal error trying to replicate layout

### ISSUE THREAD

**Issue by Podex12** [MitjaNemec/ReplicateLayout#71]
I just downloaded this plugin and trying it, but i can't get it to work. it keep prompting "fatal error" message. can someone help me? i will attach the log here.
[replicate_layout.log](https://github.com/MitjaNemec/ReplicateLayout/files/14739650/replicate_layout.log)

**Comment by MitjaNemec** [comment]
Your're using V8 compatible release of the plugin. You should use V7 compatible release of the plugin. the latest one is [2.1.3](https://github.com/MitjaNemec/ReplicateLayout/releases/tag/2.1.3)

How did you install the plugin? If you installed it via PCM then there might be a bug as PCM should prevent installation of non-compatible version.
