### ISSUE TITLE
ModuleNotFoundError("No module named 'replicate_layout.replicate_layout_GUI'")

### ISSUE THREAD

**Issue by phil123456** [MitjaNemec/ReplicateLayout#73]
the only line in the log

Kicad 7.0.5

Installed the repo content in my plugin directory

![image](https://github.com/MitjaNemec/ReplicateLayout/assets/13568652/8e36a713-df07-4305-bc11-632b2f8978cf)

**Comment by phil123456** [comment]
ok I managed to make it work by installing it with the appropriate menu

**Comment by MitjaNemec** [comment]
It is customary
