### ISSUE TITLE
Error while loading plugin - ModuleNotFoundError

### ISSUE THREAD

**Issue by Rogash1** [MitjaNemec/ReplicateLayout#8]
Hi,
I cloned the newest release 1.0.3 of the ReplicateLayout Plugin into my "user\Documents\KiCad\6.0\scripting\plugins\" folder and can't get it to run. Whenever I try to run it, I get an error window telling me to check the place_footprints_error.log.
![grafik](https://user-images.githubusercontent.com/11877158/153388310-9efb0c7e-76a0-40e3-92f9-592b67a312e8.png)
There is no error log with this name inside the plugin folder, just the replicate_layout_error.log

This logfile says "ModuleNotFoundError("No module named 'ReplicateLayout.replicate_layout_GUI'")"

Is this a bug or am I missing something?

Kind regards

Version: KiCad 6.0.1, OS: Windows 10

First edit:
I managed to get it to run by generating a package and installing it, since in the plugin repo only the 1.0.2 version exists.
So I probably just missed how the new plugin system in KiCad 6.0 works now and the only issue might be that the name for the log file is not correct in the error window. 

Second edit:
The issue still exists. After using the plugin once successfully and restarting KiCad I again have the same issue. The same issue exists if I use the 1.0.2 version from the plugin repo. After using it the first time and restarting KiCad I get the error message in the image linked above. Reinstalling does not help, either it only works randomly or just once after installing a new version with the plugin manager.

**Comment by MitjaNemec** [comment]
With KiCad V6, the correct way to install the plugin is to download one (most commonly the latest) release archive.

The files in the repo are just a source code. All the derived code and data are generated and not included in the repository by default. So you are missing the .png files for icons which are generated from .svg files and .py files for GUI which are generated using wxFormBuilder

**Comment by MitjaNemec** [comment]
If you have installed the plugin via PCM and manually, there might be some conflicts as PCM installs in one location and manualy you can install in another location. You should remove one installation

**Comment by Rogash1** [comment]
Thanks for your quick reply. With the already-built release of version 1.0.3, the error does not occur anymore.
I guess the issue can be closed or deleted now. Thank you very much.
