### ISSUE TITLE
Question: Can layouts be saved to a file?

### ISSUE THREAD

**Issue by greenscreenflicker** [MitjaNemec/ReplicateLayout#9]
I want to design custom building blocks ("blueprints"), for example for the LDO with two capacitors.
I want to save the design to be later replicated, on another design. Can that be done?
Thanks,
Michael

**Comment by MitjaNemec** [comment]
Not at the moment

For V5 I had Save/Restore plugin that implemented this functionality, but I am still working on a V6 version of this. I am really in the early stages, as V6 schematics file format changed and if we want this to work properly sot that the layout is in sync with schematics, it is not as simple as taking some code of Replicate Layout plugin

**Comment by MitjaNemec** [comment]
Closing as save restore plugin is now available (https://github.com/MitjaNemec/SaveRestoreLayout)
